#!$PREFIX/bin/bash
echo "run mysql"
mysqld_safe

password ='123456'

if[ ! $1 ]
then
    password=$1
fi

echo "use database mysql"
mysql -u $(whoami) -e "use mysql"

echo "change root password to 123456"
mysql -u $(whoami) -e "set password for 'root'@'localhost' = password('$password');"

echo "grand all privileges"
mysql -u $(whoami) -e "flush privileges;"

echo "password mysql changed succesfully!"