#!$PREFIX/bin/bash

pkg update && pkg upgrade -y

pkg install php php-apache

termux-setup-storage

sleep 5

htdocs='/sdcard/htdocs'
if [ ! -d $htdocs ];
then
  mkdir $htdocs
fi

pkg install apache2 -y

rm $PREFIX/etc/apache2/httpd.conf

mv httpd.conf $PREFIX/etc/apache2/

rm $PREFIX/bin/apachectl

chmod +x apachectl

mv apachectl $PREFIX/bin/

echo "install mariadb"
pkg install mariadb -y

echo "run mysql"
mysqld_safe -u root &

echo "use database mysql"
mysql -u $(whoami) -e "use mysql"

echo "change root password to 123456"
mysql -u $(whoami) -e "set password for 'root'@'localhost' = password('123456');"

echo "grand all privileges"
mysql -u $(whoami) -e "flush privileges;"

echo "install wget"
pkg install wget -y

echo "install unzip"
pkg install unzip -y

echo "download phpmyadmin"
wget https://files.phpmyadmin.net/phpMyAdmin/5.1.2/phpMyAdmin-5.1.2-english.zip
Kit

echo "unzip phpmyadmin"
unzip phpMyAdmin-5.1.2-english.zip

echo "rename to phpmyadmin"
mv phpMyAdmin-5.1.2-english phpmyadmin

echo "hapus phpmyadmin zip"
rm -rf phpMyAdmin-5.1.2-english.zip

echo "pindah ke htdocs"
mv phpmyadmin "$htdocs"

echo "pindah setup phpmyadmin ke htdocs"
cp config.inc.php "$htdocs/phpmyadmin"

echo "PHP and Apache2 Installed Sucessfully..."
echo "/sdcard/htdocs - is your document directory.."
echo "Place your files in /sdcard/htdocs"
echo "phpmyadmin username: root"
echo "phpmyadmin password: 123456"

echo "start apache"                                            
apachectl


