#!$PREFIX/bin/bash
password = 'root'

echo "use database mysql"
mysql -u $(whoami) -e "use mysql;"

echo "change root password to 123456"
mysql -u $(whoami) -e "set password for 'root'@'localhost' = password('$password');"

echo "grand all privileges"
mysql -u $(whoami) -e "flush privileges;"
mysql -u $(whoami) -e "quit;"

echo "password mysql changed succesfully!"